
package ch.hegarc.servicenotaire.trouver.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrouverNotaireWebServiceService", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/", wsdlLocation = "http://trouver-notaire:8080/ws/ServiceTrouverNotaire?wsdl")
public class TrouverNotaireWebServiceService
    extends Service
{

    private final static URL TROUVERNOTAIREWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TROUVERNOTAIREWEBSERVICESERVICE_EXCEPTION;
    private final static QName TROUVERNOTAIREWEBSERVICESERVICE_QNAME = new QName("http://webservice.trouver.servicenotaire.hegarc.ch/", "TrouverNotaireWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://trouver-notaire:8080/ws/ServiceTrouverNotaire?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TROUVERNOTAIREWEBSERVICESERVICE_WSDL_LOCATION = url;
        TROUVERNOTAIREWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TrouverNotaireWebServiceService() {
        super(__getWsdlLocation(), TROUVERNOTAIREWEBSERVICESERVICE_QNAME);
    }

    public TrouverNotaireWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TROUVERNOTAIREWEBSERVICESERVICE_QNAME, features);
    }

    public TrouverNotaireWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, TROUVERNOTAIREWEBSERVICESERVICE_QNAME);
    }

    public TrouverNotaireWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TROUVERNOTAIREWEBSERVICESERVICE_QNAME, features);
    }

    public TrouverNotaireWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrouverNotaireWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrouverNotaireWebService
     */
    @WebEndpoint(name = "TrouverNotaireWebServicePort")
    public TrouverNotaireWebService getTrouverNotaireWebServicePort() {
        return super.getPort(new QName("http://webservice.trouver.servicenotaire.hegarc.ch/", "TrouverNotaireWebServicePort"), TrouverNotaireWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrouverNotaireWebService
     */
    @WebEndpoint(name = "TrouverNotaireWebServicePort")
    public TrouverNotaireWebService getTrouverNotaireWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.trouver.servicenotaire.hegarc.ch/", "TrouverNotaireWebServicePort"), TrouverNotaireWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TROUVERNOTAIREWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TROUVERNOTAIREWEBSERVICESERVICE_EXCEPTION;
        }
        return TROUVERNOTAIREWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
