
package ch.hegarc.servicenotaire.trouver.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrouverNotaireWebService", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrouverNotaireWebService {


    /**
     * 
     * @param search
     * @return
     *     returns java.util.List<ch.hegarc.servicenotaire.trouver.webservice.Notaire>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/", className = "ch.hegarc.servicenotaire.trouver.webservice.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/", className = "ch.hegarc.servicenotaire.trouver.webservice.FindResponse")
    @Action(input = "http://webservice.trouver.servicenotaire.hegarc.ch/TrouverNotaireWebService/findRequest", output = "http://webservice.trouver.servicenotaire.hegarc.ch/TrouverNotaireWebService/findResponse")
    public List<Notaire> find(
        @WebParam(name = "search", targetNamespace = "")
        String search);

    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/", className = "ch.hegarc.servicenotaire.trouver.webservice.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/", className = "ch.hegarc.servicenotaire.trouver.webservice.AuthenticateResponse")
    @Action(input = "http://webservice.trouver.servicenotaire.hegarc.ch/TrouverNotaireWebService/authenticateRequest", output = "http://webservice.trouver.servicenotaire.hegarc.ch/TrouverNotaireWebService/authenticateResponse")
    public boolean authenticate(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @return
     *     returns java.util.List<ch.hegarc.servicenotaire.trouver.webservice.Notaire>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/", className = "ch.hegarc.servicenotaire.trouver.webservice.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://webservice.trouver.servicenotaire.hegarc.ch/", className = "ch.hegarc.servicenotaire.trouver.webservice.GetAllResponse")
    @Action(input = "http://webservice.trouver.servicenotaire.hegarc.ch/TrouverNotaireWebService/getAllRequest", output = "http://webservice.trouver.servicenotaire.hegarc.ch/TrouverNotaireWebService/getAllResponse")
    public List<Notaire> getAll();

}
