FROM eclipse-temurin:8-jdk

ADD target/servicenotaire_correction-1.0-SNAPSHOT-jar-with-dependencies.jar servicenotaire_correction-1.0-SNAPSHOT-jar-with-dependencies.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "servicenotaire_correction-1.0-SNAPSHOT-jar-with-dependencies.jar"]